main: net.craftingforchrist.zander.instance.ZanderInstanceMain
name: zander-instance
description: An instance used for multiple commands and events on Servers.
version: ${project.version}
author: Crafting For Christ, Ben Robson
api-version: 1.16